apiVersion: batch/v1
kind: Job
metadata:
  generateName: mp12-premium
spec:
  template:
    spec:
      containers:
      - name: mp12-premium
        image: mp12-docker
        command: ["python3", "classify.py", "DATASET=kmnist", "TYPE=cnn"]
      restartPolicy: Never
  backoffLimit: 4

